<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>false</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.11.0.20250507" />
    <PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.19041.1" />
    <PackageReference Include="Sdcb.PaddleInference.runtime.win64.mkl" Version="3.3.1.70" />
    <PackageReference Include="Sdcb.PaddleOCR" Version="3.3.1" />
    <PackageReference Include="Sdcb.PaddleOCR.Models.Local" Version="3.3.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Runtime.Serialization" />
  </ItemGroup>

  <ItemGroup>
    <None Include="$(NuGetPackageRoot)opencvsharp4.runtime.win\4.11.0.20250507\runtimes\win-x64\native\OpenCvSharpExtern.dll" CopyToOutputDirectory="PreserveNewest" Link="OpenCvSharpExtern.dll" />
    <None Include="$(NuGetPackageRoot)opencvsharp4.runtime.win\4.11.0.20250507\runtimes\win-x64\native\opencv_videoio_ffmpeg4110_64.dll" CopyToOutputDirectory="PreserveNewest" Link="opencv_videoio_ffmpeg4110_64.dll" />
  </ItemGroup>

</Project>
