<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AI.Vision.IOInspector.Domain\AI.Vision.IOInspector.Domain.csproj" />
    <ProjectReference Include="..\AI.Vision.IOInspector.Application\AI.Vision.IOInspector.Application.csproj" />
    <ProjectReference Include="..\AI.Vision.IOInspector.Infrastructure\AI.Vision.IOInspector.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Web.Extensions" />
    <Reference Include="MVSDK_Net">
      <HintPath>..\Native\VLAD\MVSDK_Net.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="OpenCvSharp">
      <HintPath>..\Native\VLAD\OpenCvSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="OpenCvSharp.Blob">
      <HintPath>..\Native\VLAD\OpenCvSharp.Blob.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="OpenCvSharp.Extensions">
      <HintPath>..\Native\VLAD\OpenCvSharp.Extensions.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="OpenCvSharp.UserInterface">
      <HintPath>..\Native\VLAD\OpenCvSharp.UserInterface.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Native\VLAD\VLAD_SDK.dll" Link="NativeReferences\VLAD\VLAD_SDK.dll" />
    <None Include="..\Native\VLAD\VLAD_Ctrl.dll" Link="NativeReferences\VLAD\VLAD_Ctrl.dll" />
    <None Include="..\Native\VLAD\MVSDKmd.dll" Link="NativeReferences\VLAD\MVSDKmd.dll" />
    <None Include="..\Native\VLAD\LibVLCSharp.dll" Link="NativeReferences\VLAD\LibVLCSharp.dll" />
    <None Include="..\Native\VLAD\libvlc.dll" Link="NativeReferences\VLAD\libvlc.dll" />
    <None Include="..\Native\VLAD\libvlccore.dll" Link="NativeReferences\VLAD\libvlccore.dll" />
    <None Include="..\Native\VLAD\OpenCvSharpExtern.dll" Link="NativeReferences\VLAD\OpenCvSharpExtern.dll" />
    <None Include="..\Native\VLAD\opencv_ffmpeg400_64.dll" Link="NativeReferences\VLAD\opencv_ffmpeg400_64.dll" />
    <None Include="..\Native\VLAD\opencv_world453.dll" Link="NativeReferences\VLAD\opencv_world453.dll" />
    <None Include="..\Native\VLAD\jsoncpp.dll" Link="NativeReferences\VLAD\jsoncpp.dll" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="LegacyVlad\VladNativeMethods.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <PlatformTarget>x64</PlatformTarget>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <OutputType>Library</OutputType>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
